HL_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # (r'^inplaceeditform/', include('inplaceeditform.urls')),

    re_path(r'', include(('labeller.urls', 'labeller'), namespace='labeller')),
    re_path(r'', include(('export.urls', 'export'), namespace='export')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:  # pragma: no cover
    # Static files for local dev, so we don't have to collectstatic and such
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

export/urls.py
from django.urls import path, include, re_path
from . import views
urlpatterns = [

]

labeller/urls.py
"""
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""


from django.urls import path, include, re_path
from . import views
urlpatterns = [

        path('add_note_to_slide', views.add_note_to_slide, name='add_note_to_slide'),
        path('add_tissue_type_to_slide/', views.add_tissue_type_to_slide, name='add_tissue_type_to_slide'),

    ############################################################################################
    ################################ URLS THAT SERVE HTML PAGES ################################

    ################################ base.html nav bar ################################

    re_path(r'^$', views.index, name='index'),

    re_path(r'^regions/$', views.regions, name='regions'),

    re_path(r'^slides/$', views.slides, name='slides'),

    re_path(r'^diagnoses/$', views.diagnoses, name='diagnoses'),

    # Page for viewing all projects created when uploading cells - under construction
    re_path(r'^projects/$', views.projects, name='projects'),

    # Page for viewing labelling stats/progress - under construction
    re_path(r'^stats/$', views.stats, name='stats'),

    ####################### other html pages (data labelling/export) #######################

    re_path(r'^project/(?P<project_id>\d+)/',
            views.project, name='project'),

    re_path(r'^diagnosis/(?P<diagnosis_id>\d+)/',
            views.diagnosis, name='diagnosis'),

    re_path(r'^all_cells_for_diagnosis/(?P<diagnosis_id>\d+)/',
            views.all_cells_for_diagnosis, name='all_cells_for_diagnosis'),

    re_path(r'^all_cells_for_diagnosis2/(?P<diagnosis_id>\d+)/',
            views.all_cells_for_diagnosis2, name='all_cells_for_diagnosis2'),

    re_path(r'^cell_redirect/(?P<cell_pk>\d+)/',
            views.cell_redirect, name='cell_redirect'),

    # Page for labelling a slide
    re_path(r'^label_slide/(?P<slide_id>\d+)/$',
            views.label_slide, name='label_slide'),

    # testpage for bootstrap
    re_path(r'^label_slide_bootstrap/(?P<slide_id>\d+)/$',
            views.label_slide, name='label_slide'),
    re_path(r'^bootstrap_test.html',
            views.bootstrap_test, name='bootstrap_test'),

    # Page for labelling a region of interest
    re_path(r'^label_region_fabric/(?P<region_id>\d+)/$',
            views.label_region_fabric, name='label_region_fabric'),

    # Not currently in use - may require fixing
    # Page for labelling a cell in given project
    re_path(r'^label_cells_in_project/(?P<project_id>\d+)/$',
            views.label_cells_in_project, name='label_cells_in_project'),

    # Page for exporting Project Data
    re_path(r'^export_project_data/$', views.export_project_data,
            name='export_project_data'),


    re_path(r'export_all_cell_annotations_for_user/$',
            views.export_all_cell_annotations_for_user, name='export_all_cell_annotations_for_user'),
    # Experimental
    # Page for exporting Project Data
    re_path(r'^export/', views.export_cell_data, name='export_cell_data'),

    re_path(r'^export_cells/$', views.export_all_cell_annotations_user,
            name='export_all_cell_annotations_user'),



    #******************************************************************************************#


    ################################################################################################
    ###################################### USER ACCOUNT HANDLING ###################################

    # Add Django site authentication URLS (login, logout, password management...)
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),

    # Add user registration page
    path('register/', views.register, name='register'),

    #******************************************************************************************#


    ########################################################################################################
    ############################################ AJAX FUNCTIONS ############################################
    re_path(r'^generic_ajax_get/', views.generic_ajax_get,
            name='generic_ajax_get'),

#***************************** ADD NOTES ***************************#
        # path('add_note_to_slide/', views.add_note_to_slide, name='add_note_to_slide'),
        # path('slides/add_note_to_slide/', views.CreateSlideNoteView.as_view(), name="add_note_to_slide"),
        # re_path(r'^add_note_to_slide/', views.CreateSlideNoteView.as_view(), name='add_note_to_slide'),
        # path('slides/get_slide_notes/', views.get_slide_notes, name='get_slide_notes'),
    re_path(r'^add_note_to_slide/', views.add_note_to_slide, name='add_note_to_slide'),
    #************************* SLIDE POSTS *************************#
    re_path(r'^add_diagnosis_to_slide/',
            views.add_diagnosis_to_slide, name='add_diagnosis_to_slide'),
    # Called remove and not delete because diagnosis is not deleted. It is just removed as a ManyToMany relation from slide
    re_path(r'^remove_diagnosis_from_slide/',
            views.remove_diagnosis_from_slide, name='remove_diagnosis_from_slide'),

    re_path(r'^get_number_of_slides_with_diagnosis_name/',
            views.get_number_of_slides_with_diagnosis_name, name='get_number_of_slides_with_diagnosis_name'),

    #************************* REGION POSTS *************************#
    re_path(r'^add_new_region/', views.add_new_region,
            name='add_new_region'),
    re_path(r'^delete_region/', views.delete_region, name='delete_region'),
    re_path(r'^toggle_region_complete_seg/',
            views.toggle_region_complete_seg, name='toggle_region_complete_seg'),
    re_path(r'^toggle_region_complete_class/',
            views.toggle_region_complete_class, name='toggle_region_complete_class'),

    #************************* PROJECT POSTS *************************#
    path('create_project', views.create_project, name="create_project"),




    #************************* CELL GETS *************************#
    re_path(r'^get_cell_feature_form/', views.get_cell_feature_form,
            name='get_cell_feature_form'),

    re_path(r'^get_cell_json/', views.get_cell_json, name='get_cell_json'),

    re_path(r'^get_all_cells_generic/', views.get_all_cells_generic,
            name='get_all_cells_generic'),

    re_path(r'^get_all_cells_in_project/',
            views.get_all_cells_in_project, name='get_all_cells_in_project'),

    re_path(r'^get_all_cells_in_slide/',
            views.get_all_cells_in_slide, name='get_all_cells_in_slide'),

    re_path(r'^get_all_cells_in_region/',
            views.get_all_cells_in_region, name='get_all_cells_in_region'),

    #************************* CELL AND CELLTYPE POSTS *************************#
    #re_path(r'^add_new_cell/', views.add_new_cell, name='add_new_cell'),

    # Add new cell with box (AJAX)
    re_path(r'^add_new_cell_box/', views.add_new_cell_box,
            name='add_new_cell_box'),
    re_path(r'^delete_cell/', views.delete_cell, name='delete_cell'),
    re_path(r'^change_cell_location/', views.change_cell_location,
            name='change_cell_location'),
    re_path(r'^update_cell_class/', views.update_cell_class,
            name='update_cell_class'),
    re_path(r'^add_additional_cellType_to_cell',
            views.add_additional_cellType_to_cell, name='add_additional_cellType_to_cell'),

    #******************************************************************************************#

    ####################################################################################
    ################################ DROPZONE UPLOADERS ################################
    # Handles uploaded cell images
    #path('dropzone_image', views.dropzone_image, name='dropzone_image'),
    #re_path(r'^label_cell_fabric/(?P<project_id>\d+)/dropzone_image', views.dropzone_image_w_projectID, name='dropzone_image_w_projectID'),
    re_path(r'^label_cells_in_project/(?P<project_id>\d+)/dropzone_image',
            views.dropzone_image_w_projectID, name='dropzone_image_w_projectID'),

    # Handles dropzone uploaded slides or slide spreadsheets
    #re_path(r'^label_cells_in_project/dropzone_slide', views.dropzone_slide, name='dropzone_slide_upload'),
    re_path(r'^slides/dropzone_slide', views.dropzone_slide,
            name='dropzone_slide_upload'),

    #***********************************************************************************#

        # CUSTOM ERROR PAGES
    path('403/', views.error_403, name='403_forbidden'),

]

# Show all cells
#	re_path(r'^cells2/$', views.cells2, name='cells2'),

# Page for labelling a slide
#	re_path(r'^label_slide_overlay/(?P<slide_id>\d+)/$', views.label_slide_overlay, name='label_slide_overlay'),

# Page for labelling a region of interest
#re_path(r'^label_region/(?P<region_id>\d+)/$', views.label_region, name='label_region'),

# # Page for exporting data
# re_path(r'^data_export/$', views.data_export, name='data_export'),

# Label next region
#	re_path(r'^next_region/', views.next_region, name='next_region'),

# # Change cell location (AJAX)
# re_path(r'^get_cell_center_relative_to_slide/', views.get_cell_center_relative_to_slide, name='get_cell_center_relative_to_slide'),

# Get cell information (AJAX)
#	re_path(r'^get_cellType/', views.get_cellType, name='get_cellType'),

# re_path(r'^blank_request/', views.blank_request, name='blank_request'),

# Page for labelling individual cell

labeller/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from labeller.models import CellFeature

from .models import Project, Region, Cell, Slide

class RegionForm(forms.ModelForm):
	class Meta:
		model = Region
		fields = ['rid', 'slide', 'image']
		labels = {'rid': '', 'slide': '', 'image': ''}

# Form for cell upload
class CellForm(forms.ModelForm):
  class Meta:
    model = Cell
    fields = {'image'}

# Form for creating a new project
class ProjectForm(forms.ModelForm):
  class Meta:
    model = Project
    fields = {'name'}


# Create user sign up form
class UserForm(UserCreationForm):
  first_name = forms.CharField()
  last_name  = forms.CharField()
  email      = forms.EmailField()

  class Meta:
    model = User
    fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

# https://medium.com/swlh/django-forms-for-many-to-many-fields-d977dec4b024
# https://medium.com/analytics-vidhya/django-how-to-pass-the-user-object-into-form-classes-ee322f02948c
class CellFeatureForm(forms.ModelForm): 
  
  class Meta:
    model = Cell
    fields = ['name','cellFeatures']

  cellFeatures = forms.ModelMultipleChoiceField(
      queryset=CellFeature.objects.all(),
      widget=forms.CheckboxSelectMultiple
  )    


class DiagnosisForm(forms.Form):
    name = forms.CharField(
        max_length=64,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Diagnosis"
        })
    )
    abbreviation = forms.CharField(
        max_length=8,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Dx"
        })
    )

labeller/templates/labeller/add_note_to_slide.html
{% extends 'labeller/base2.html' %}
{% load static %}

{% block title %} Add Note {% endblock title %}

{% block content %}

{% if user.is_authenticated %}

   <div id="div_notes_form_{{slide.sid}}" class="mt-2 form-group">

        <form method="POST" id="add_note_to_slide_{{slide.sid}}_form">
            {% csrf_token %}
            {{ form.as_p }}
            <button id="add_note_to_slide_{{slide.sid}}_submit" class="btn btn-slide-info" style="font-size:1rem; padding:.2rem 0.5rem 0.1rem .5rem !important">
                Add note
            </button>
        </form>
       <!-- <form action="#" id="form_slide_notes_{{slide.sid}}" class="notes_form">
            <input type="text">
            <button name="action" value="add note" class="btn btn-slide-info"        style="font-size:1rem; padding:.2rem 0.5rem 0.1rem .5rem !important">Add note
            </button>
       </form> -->
   </div> 

   <script>
       
   </script>

{% else %}

   You do note have access to this page.

{% endif %}



{% endblock content %}

labeller/templates/labeller/base.html
<!doctype html>
{% load static %}
<head>
	<title>{% block title %}Hemepath{% endblock %}</title>

	<link rel="shortcut icon" type="image/png" href="{% static 'labeller/images/favicon.ico' %}"/>

  <link rel="stylesheet" href="{% static 'labeller/jquery-ui-1.12.1.custom/jquery-ui.min.css' %}">
  <script src="{% static 'labeller/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'labeller/jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>

  <script src="{% static 'labeller/ajax_setup.js' %}"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'labeller/bootstrap-5.0.2-dist/css/bootstrap.min.css' %}">
  <script src="{% static 'labeller/bootstrap-5.0.2-dist/js/bootstrap.bundle.min.js' %}"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

  <link rel="stylesheet" type="text/css" href="{% static 'labeller/style.css' %}">
  {% block head %} {% endblock head %}

</head>

<body>
<h1> HemeLabel: Hematopoietic Cell Labeller </h1>

<ul class="row_menu">
	<li><a href="{% url 'labeller:index' %}">Home</a></li>

  {% if user.is_authenticated %}
  <script>console.log("User is:", '{{user}}')</script>

    <li><a href="{% url 'labeller:diagnoses' %}">Diagnoses</a></li>
    <li><a href="{% url 'labeller:slides' %}">Slides</a></li>
    <li><a href="{% url 'labeller:regions' %}">Regions</a></li>
    <li><a href="{% url 'labeller:projects' %}">Projects</a></li>


    <li><a href="{% url 'labeller:logout' %}?next={% url 'labeller:index' %}">Logout</a></li>

  {% else %}
  
    <li><a href="{% url 'labeller:login' %}?next={% url 'labeller:index' %}">Login</a></li>
    <li><a href="{% url 'labeller:register' %}">Sign Up</a></li>
  
  {% endif %}
</ul>

{% block content %} {% endblock content %}

</body>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p>Copyright &copy; Gregory M. Goldgof</p>
            </div>
            <div class="col-md-6 text-md-end">
                <a href="#" class="text-dark">Terms of Use</a> 
                <span class="text-muted mx-2">|</span> 
                <a href="#" class="text-dark">Privacy Policy</a>
            </div>
        </div>
    </div>
</footer>


{% block scripts %} {% endblock scripts %}

labeller/templates/labeller/base2.html
<!doctype html>
{% load static %}
<head>
	<title>{% block title %}Hemepath{% endblock %}</title>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="shortcut icon" type="image/png" href="{% static 'labeller/images/favicon.ico' %}"/>

    <!-- <link rel="stylesheet" href="{% static 'labeller/jquery-ui-1.12.1.custom/jquery-ui.min.css' %}">
    <script src="{% static 'labeller/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'labeller/jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>

    <script src="{% static 'labeller/ajax_setup.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'labeller/bootstrap-5.0.2-dist/css/bootstrap.min.css' %}">
    <script src="{% static 'labeller/bootstrap-5.0.2-dist/js/bootstrap.bundle.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script> -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script> -->
    <script src="{% static 'labeller/popper.min.js' %}"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <script src="{% static 'labeller/ajax_setup.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

    <link rel="stylesheet" type="text/css" href="{% static 'labeller/style2.css' %}">
    {% block head %} {% endblock head %}

</head>

<body>


<!-- Navigation -->

<nav class="navbar navbar-expand-md navbar-dark plum ">
	<div class="container-fluid ">
{% comment %}		<a class="navbar-brand" href="{% url 'labeller:index' %}"><img src="{% static 'labeller/images/HemeLogo1.png' %}"></a>
{% endcomment %}
        <div class="navbar-brand">HemeLabel</div>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse " id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'labeller:index' %}">Home</a></li>

                {% if user.is_authenticated %}
                <script>console.log("User is:", '{{user}}')</script>
                <li class="nav-item"><a class="nav-link" href="{% url 'labeller:diagnoses' %}">Diagnoses</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'labeller:slides' %}">Slides</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'labeller:regions' %}">Regions</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'labeller:projects' %}">Projects</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'labeller:logout' %}?next={% url 'labeller:index' %}">Logout</a></li>
              
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'labeller:login' %}?next={% url 'labeller:index' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'labeller:register' %}">Sign Up</a></li>
                
                {% endif %}

			</ul>

		</div>

 	</div>
</nav>



{% block content %} {% endblock content %}
</body>
<footer>
    <div class="container-fluid plum">
        <div class="row text-center">
            <div class="col-12">
                <!-- <hr class="light-100"> -->
                <h5 class="copy_text">&copy; G. Goldgof<h5>
            </div>
    
        </div>
    </div>
    
</footer>

<!-- <footer>
    <div class="container bg-dark">
        <div class="row">
            <div class="col-md-6">
                <p>Copyright &copy; Gregory M. Goldgof</p>
            </div>
            <div class="col-md-6 text-md-end">
                <a href="#" class="text-light">Terms of Use</a> 
                <span class="text-muted mx-2">|</span> 
                <a href="#" class="text-light">Privacy Policy</a>
            </div>
        </div>
    </div>
</footer> -->


{% block scripts %} {% endblock scripts %}

labeller/templates/labeller/bootstrap_test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'labeller/images/favicon.ico' %}"/>

    <title>Basic Bootstrap Template</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'labeller/bootstrap-5.0.2-dist/css/bootstrap.min.css' %}">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">  -->
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a href="#" class="navbar-brand">Tutorial Republic</a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav">
                    <a href="#" class="nav-item nav-link active">Home</a>
                    <a href="#" class="nav-item nav-link">Services</a>
                    <a href="#" class="nav-item nav-link">About</a>
                    <a href="#" class="nav-item nav-link">Contact</a>
                </div>
                <div class="navbar-nav ms-auto">  
                    <a href="#" class="nav-item nav-link">Register</a>            	
                    <a href="#" class="nav-item nav-link">Login</a>
                </div>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="p-5 my-4 bg-light rounded-3">
            <h1>Learn to Create Websites</h1>
            <p class="lead">In today's world internet is the most popular way of connecting with the people. At <a href="https://www.tutorialrepublic.com" class="text-success" target="_blank">tutorialrepublic.com</a> you will learn the essential web development technologies along with real life practice examples, so that you can create your own website to connect with the people around the world.</p>
            <p><a href="https://www.tutorialrepublic.com" target="_blank" class="btn btn-success btn-lg">Get started today</a></p>
        </div>
        <div class="row">
            <div class="col-md-4">
                <h2>HTML</h2>
                <p>HTML is the standard markup language for describing the structure of the web pages. Our HTML tutorials will help you to understand the basics of latest HTML5 language, so that you can create your own web pages or website.</p>
                <p><a href="https://www.tutorialrepublic.com/html-tutorial/" target="_blank" class="btn btn-success">Learn More &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>CSS</h2>
                <p>CSS is used for describing the presentation of web pages. CSS can save a lot of time and effort. Our CSS tutorials will help you to learn the essentials of latest CSS3, so that you can control the style and layout of your website.</p>
                <p><a href="https://www.tutorialrepublic.com/css-tutorial/" target="_blank" class="btn btn-success">Learn More &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Bootstrap</h2>
                <p>Bootstrap is a powerful front-end framework for faster and easier web development. Our Bootstrap tutorials will help you to learn all the features of latest Bootstrap 4 framework so that you can easily create responsive websites.</p>
                <p><a href="https://www.tutorialrepublic.com/twitter-bootstrap-tutorial/" target="_blank" class="btn btn-success">Learn More &raquo;</a></p>
            </div>
        </div>
        <hr>
        <footer>
            <div class="row">
                <div class="col-md-6">
                    <p>Copyright &copy; 2021 Tutorial Republic</p>
                </div>
                <div class="col-md-6 text-md-end">
                    <a href="#" class="text-dark">Terms of Use</a> 
                    <span class="text-muted mx-2">|</span> 
                    <a href="#" class="text-dark">Privacy Policy</a>
                </div>
            </div>
        </footer>
    </div>


    <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
        <label class="form-check-label" for="inlineCheckbox1">1</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2">
        <label class="form-check-label" for="inlineCheckbox2">2</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3" disabled>
        <label class="form-check-label" for="inlineCheckbox3">3 (disabled)</label>
      </div>
</body>
</html>

labeller/templates/labeller/cells2.html
<!-- NOT CURRENTLY IN USE -->

{% extends "labeller/base.html" %}


{% block content %}


<h2>Cells</h2>

{% for slide, region_list in slide_list %}
	<li>Slide: {{slide}}</li>
		{% for region, cell_list in region_list %}
		<ul ><li>
			Region: {{region}}
			{% for cell, cellForm in cell_list|slice:"0:20" %}
				<ul class='slide_list slide_list_box'>
					<li> {{ cell.cid}}</li> 
					
					<li><img src="{{cell.image}}"></li>
					<li id='form_{{cell.cid}}'>{{cellForm.as_p}}</li>
					<button class='button_get_from' id="button_{{cell.cid}}" type="button">Get Form</button>
					<li id='form2_{{cell.cid}}'></li>
				</ul>
			{% endfor %}

		</li></ul>
		{% endfor %}
{% endfor %}

<script> 
$(document).ready(function() {

   $('.button_get_from').on('click', function() {
   		var cid = $(this).attr('id').substr('button_'.length)
    	console.log('click', cid)
    
    	$.get('/get_cell_feature_form/', {'cid': cid}, function(response) {
    		$('#form2_'+cid).html(response);
    	});    
  	});

});

</script>

{% endblock content %}

labeller/templates/labeller/register.html
{% extends 'labeller/base.html' %} 

{% block content %}

{% comment %} <script>
    {% if messages %}
        {% for message in messages %}
            alert('{{message}}')
        {% endfor %}
    {% endif %}
</script> {% endcomment %}

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <br>
  <input type="submit" value="Register"/>
</form>

{% endblock %}

labeller/templates/labeller/signup.html
{% extends 'labeller/base.html' %}

{% block content %}

  <h2>Create an Accoutn</h2>

  <form method='post'>
    {% csrf_token %}
      {{ form.as_p }}
      <button type='submit' class='btn btn-success'>Register</button>
  </form>

{% endblock %}