HL_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # (r'^inplaceeditform/', include('inplaceeditform.urls')),

    re_path(r'', include(('labeller.urls', 'labeller'), namespace='labeller')),
    re_path(r'', include(('export.urls', 'export'), namespace='export')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:  # pragma: no cover
    # Static files for local dev, so we don't have to collectstatic and such
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

export/urls.py
from django.urls import path, include, re_path
from . import views
urlpatterns = [

]

labeller/urls.py
from django.urls import path, include, re_path
from . import views
urlpatterns = [

        path('add_note_to_slide', views.add_note_to_slide, name='add_note_to_slide'),
        path('add_tissue_type_to_slide/', views.add_tissue_type_to_slide, name='add_tissue_type_to_slide'),

    ############################################################################################
    ################################ URLS THAT SERVE HTML PAGES ################################

    ################################ base.html nav bar ################################

    re_path(r'^$', views.index, name='index'),

    re_path(r'^regions/$', views.regions, name='regions'),

    re_path(r'^slides/$', views.slides, name='slides'),

    re_path(r'^diagnoses/$', views.diagnoses, name='diagnoses'),

    # Page for viewing all projects created when uploading cells - under construction
    re_path(r'^projects/$', views.projects, name='projects'),

    # Page for viewing labelling stats/progress - under construction
    re_path(r'^stats/$', views.stats, name='stats'),

    ####################### other html pages (data labelling/export) #######################

    re_path(r'^project/(?P<project_id>\d+)/',
            views.project, name='project'),

    re_path(r'^diagnosis/(?P<diagnosis_id>\d+)/',
            views.diagnosis, name='diagnosis'),

    re_path(r'^all_cells_for_diagnosis/(?P<diagnosis_id>\d+)/',
            views.all_cells_for_diagnosis, name='all_cells_for_diagnosis'),

    re_path(r'^all_cells_for_diagnosis2/(?P<diagnosis_id>\d+)/',
            views.all_cells_for_diagnosis2, name='all_cells_for_diagnosis2'),

    re_path(r'^cell_redirect/(?P<cell_pk>\d+)/',
            views.cell_redirect, name='cell_redirect'),

    # Page for labelling a slide
    re_path(r'^label_slide/(?P<slide_id>\d+)/$',
            views.label_slide, name='label_slide'),

    # testpage for bootstrap
    re_path(r'^label_slide_bootstrap/(?P<slide_id>\d+)/$',
            views.label_slide, name='label_slide'),
    re_path(r'^bootstrap_test.html',
            views.bootstrap_test, name='bootstrap_test'),

    # Page for labelling a region of interest
    re_path(r'^label_region_fabric/(?P<region_id>\d+)/$',
            views.label_region_fabric, name='label_region_fabric'),

    # Not currently in use - may require fixing
    # Page for labelling a cell in given project
    re_path(r'^label_cells_in_project/(?P<project_id>\d+)/$',
            views.label_cells_in_project, name='label_cells_in_project'),

    # Page for exporting Project Data
    re_path(r'^export_project_data/$', views.export_project_data,
            name='export_project_data'),


    re_path(r'export_all_cell_annotations_for_user/$',
            views.export_all_cell_annotations_for_user, name='export_all_cell_annotations_for_user'),
    # Experimental
    # Page for exporting Project Data
    re_path(r'^export/', views.export_cell_data, name='export_cell_data'),

    re_path(r'^export_cells/$', views.export_all_cell_annotations_user,
            name='export_all_cell_annotations_user'),



    #******************************************************************************************#


    ################################################################################################
    ###################################### USER ACCOUNT HANDLING ###################################

    # Add Django site authentication URLS (login, logout, password management...)
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),

    # Add user registration page
    path('register/', views.register, name='register'),

    #******************************************************************************************#


    ########################################################################################################
    ############################################ AJAX FUNCTIONS ############################################
    re_path(r'^generic_ajax_get/', views.generic_ajax_get,
            name='generic_ajax_get'),

#***************************** ADD NOTES ***************************#
        # path('add_note_to_slide/', views.add_note_to_slide, name='add_note_to_slide'),
        # path('slides/add_note_to_slide/', views.CreateSlideNoteView.as_view(), name="add_note_to_slide"),
        # re_path(r'^add_note_to_slide/', views.CreateSlideNoteView.as_view(), name='add_note_to_slide'),
        # path('slides/get_slide_notes/', views.get_slide_notes, name='get_slide_notes'),
    re_path(r'^add_note_to_slide/', views.add_note_to_slide, name='add_note_to_slide'),
    #************************* SLIDE POSTS *************************#
    re_path(r'^add_diagnosis_to_slide/',
            views.add_diagnosis_to_slide, name='add_diagnosis_to_slide'),
    # Called remove and not delete because diagnosis is not deleted. It is just removed as a ManyToMany relation from slide
    re_path(r'^remove_diagnosis_from_slide/',
            views.remove_diagnosis_from_slide, name='remove_diagnosis_from_slide'),

    re_path(r'^get_number_of_slides_with_diagnosis_name/',
            views.get_number_of_slides_with_diagnosis_name, name='get_number_of_slides_with_diagnosis_name'),

    #************************* REGION POSTS *************************#
    re_path(r'^add_new_region/', views.add_new_region,
            name='add_new_region'),
    re_path(r'^delete_region/', views.delete_region, name='delete_region'),
    re_path(r'^toggle_region_complete_seg/',
            views.toggle_region_complete_seg, name='toggle_region_complete_seg'),
    re_path(r'^toggle_region_complete_class/',
            views.toggle_region_complete_class, name='toggle_region_complete_class'),

    #************************* PROJECT POSTS *************************#
    path('create_project', views.create_project, name="create_project"),




    #************************* CELL GETS *************************#
    re_path(r'^get_cell_feature_form/', views.get_cell_feature_form,
            name='get_cell_feature_form'),

    re_path(r'^get_cell_json/', views.get_cell_json, name='get_cell_json'),

    re_path(r'^get_all_cells_generic/', views.get_all_cells_generic,
            name='get_all_cells_generic'),

    re_path(r'^get_all_cells_in_project/',
            views.get_all_cells_in_project, name='get_all_cells_in_project'),

    re_path(r'^get_all_cells_in_slide/',
            views.get_all_cells_in_slide, name='get_all_cells_in_slide'),

    re_path(r'^get_all_cells_in_region/',
            views.get_all_cells_in_region, name='get_all_cells_in_region'),

    #************************* CELL AND CELLTYPE POSTS *************************#
    #re_path(r'^add_new_cell/', views.add_new_cell, name='add_new_cell'),

    # Add new cell with box (AJAX)
    re_path(r'^add_new_cell_box/', views.add_new_cell_box,
            name='add_new_cell_box'),
    re_path(r'^delete_cell/', views.delete_cell, name='delete_cell'),
    re_path(r'^change_cell_location/', views.change_cell_location,
            name='change_cell_location'),
    re_path(r'^update_cell_class/', views.update_cell_class,
            name='update_cell_class'),
    re_path(r'^add_additional_cellType_to_cell',
            views.add_additional_cellType_to_cell, name='add_additional_cellType_to_cell'),

    #******************************************************************************************#

    ####################################################################################
    ################################ DROPZONE UPLOADERS ################################
    # Handles uploaded cell images
    #path('dropzone_image', views.dropzone_image, name='dropzone_image'),
    #re_path(r'^label_cell_fabric/(?P<project_id>\d+)/dropzone_image', views.dropzone_image_w_projectID, name='dropzone_image_w_projectID'),
    re_path(r'^label_cells_in_project/(?P<project_id>\d+)/dropzone_image',
            views.dropzone_image_w_projectID, name='dropzone_image_w_projectID'),

    # Handles dropzone uploaded slides or slide spreadsheets
    #re_path(r'^label_cells_in_project/dropzone_slide', views.dropzone_slide, name='dropzone_slide_upload'),
    re_path(r'^slides/dropzone_slide', views.dropzone_slide,
            name='dropzone_slide_upload'),

    #***********************************************************************************#

        # CUSTOM ERROR PAGES
    path('403/', views.error_403, name='403_forbidden'),

]

# Show all cells
#	re_path(r'^cells2/$', views.cells2, name='cells2'),

# Page for labelling a slide
#	re_path(r'^label_slide_overlay/(?P<slide_id>\d+)/$', views.label_slide_overlay, name='label_slide_overlay'),

# Page for labelling a region of interest
#re_path(r'^label_region/(?P<region_id>\d+)/$', views.label_region, name='label_region'),

# # Page for exporting data
# re_path(r'^data_export/$', views.data_export, name='data_export'),

# Label next region
#	re_path(r'^next_region/', views.next_region, name='next_region'),

# # Change cell location (AJAX)
# re_path(r'^get_cell_center_relative_to_slide/', views.get_cell_center_relative_to_slide, name='get_cell_center_relative_to_slide'),

# Get cell information (AJAX)
#	re_path(r'^get_cellType/', views.get_cellType, name='get_cellType'),

# re_path(r'^blank_request/', views.blank_request, name='blank_request'),

# Page for labelling individual cell
# No longer in use - was for non-existed label_cell individual html page
#re_path(r'^label_cell/(?P<cell_id>\d+)/$', views.label_cell, name='label_cell'),

# Page for viewing Whole Slide IMages
#	re_path(r'^normal_cell_labeller/$', views.normal_cell_labeller, name= 'normal_cell_labeller'),

# Page for directly uploading cells enmasse.
# re_path(r'^upload_cells/$', views.upload_cells, name='upload_cells'),

# # Show all cells
# re_path(r'^cells/$', views.cells, name='cells'),

# # Add new region
# re_path(r'^new_region/$', views.new_region, name='new_region'),

# Page for viewing Whole Slide IMages

labeller/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from labeller.models import CellFeature

from .models import Project, Region, Cell, Slide

class RegionForm(forms.ModelForm):
	class Meta:
		model = Region
		fields = ['rid', 'slide', 'image']
		labels = {'rid': '', 'slide': '', 'image': ''}

# Form for cell upload
class CellForm(forms.ModelForm):
  class Meta:
    model = Cell
    fields = {'image'}

# Form for creating a new project
class ProjectForm(forms.ModelForm):
  class Meta:
    model = Project
    fields = {'name'}


# Create user sign up form
class UserForm(UserCreationForm):
  first_name = forms.CharField()
  last_name  = forms.CharField()
  email      = forms.EmailField()

  class Meta:
    model = User
    fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

# https://medium.com/swlh/django-forms-for-many-to-many-fields-d977dec4b024
# https://medium.com/analytics-vidhya/django-how-to-pass-the-user-object-into-form-classes-ee322f02948c
class CellFeatureForm(forms.ModelForm): 
  
  class Meta:
    model = Cell
    fields = ['name','cellFeatures']

  cellFeatures = forms.ModelMultipleChoiceField(
      queryset=CellFeature.objects.all(),
      widget=forms.CheckboxSelectMultiple
  )    


class DiagnosisForm(forms.Form):
    name = forms.CharField(
        max_length=64,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Diagnosis"
        })
    )
    abbreviation = forms.CharField(
        max_length=8,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Dx"
        })
    )

labeller/templates/labeller/partials/add_slide_note.html
{% load static %}

{% if user.is_authenticated %}
{{slide.sid}}
   <div id="slide_{{slide.sid}}_note_form" class="container-fluid mt-2 form-group">

        <div class="form-group">
            <form method="POST" action="{% url 'labeller:add_note_to_slide' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button id="add_note_to_slide_{{slide.sid}}_submit" class="btn btn-slide-info" style="font-size:1rem; padding:.2rem 0.5rem 0.1rem .5rem !important">
                    Add note
                </button>
            </form>
        </div>

    </div> 

    <script>
        var slide_sid = "{{ slide.sid }}";
        console.log(slide_sid);
        document.getElementById("note_sid").value = slide_sid;
    </script>

{% else %}
    <p>You do not have access to this page.</p>
{% endif %}

labeller/templates/labeller/partials/cell_summary.html
{% load static %}
<div id='slide_info_row'></div>
<script src="{% static 'labeller/CellSummary.js' %}"></script>

<script>
  current_url = window.location.href;
  if (current_url.search('label_slide') != -1) {
    var id_type = 'sid'
    var id_val = '{{slide.sid}}'
  }
  else if (current_url.search('label_region') != -1){
    var id_type = 'rid'
    var id_val = '{{region.rid}}'
  }
  else if (current_url.search('diagnosis') != -1){
    var id_type = 'diagnosis_pk'
    var id_val = '{{diagnosis.pk}}'
  }
  else if (current_url.search('project') != -1){
    var id_type = 'project_pk'
    var id_val = '{{project.pk}}'
  }
  else {
    console.log("Error in slide_summary.html")
  }
  var cellSummary = new CellSummary(id_type, id_val);
  $('#slide_info_row').append(cellSummary.getULForSlide());
  // $('#slide_info_row').append(cellSummary.getNewULForSlide());

  cellSummary.addInfoButtonOnClick();
  
  //$('.bigtable').hide();
</script>

<script>
  $ (document).ready(function() {
    $('#slide_info_'+id_type+'_'+id_val).trigger( "click" );
    console.log('#slide_info'+id_type+'_'+id_val);
    console.log($('#slide_info'+id_type+'_'+id_val))

  });
</script>

labeller/templates/labeller/partials/cell_summary2.html
{% load static %}
<div id='slide_info_row'></div>
<script src="{% static 'labeller/CellSummary.js' %}"></script>

<script>
  current_url = window.location.href;
  if (current_url.search('label_slide') != -1) {
    var id_type = 'sid'
    var id_val = '{{slide.sid}}'
  }
  else if (current_url.search('label_region') != -1){
    var id_type = 'rid'
    var id_val = '{{region.rid}}'
  }
  else if (current_url.search('diagnosis') != -1){
    var id_type = 'diagnosis_pk'
    var id_val = '{{diagnosis.pk}}'
  }
  else if (current_url.search('project') != -1){
    var id_type = 'project_pk'
    var id_val = '{{project.pk}}'
  }
  else {
    console.log("Error in slide_summary.html")
  }
  var cellSummary = new CellSummary(id_type, id_val);
  // $('#slide_info_row').append(cellSummary.getULForSlide());
  $('#slide_info_row').append(cellSummary.getNewULForSlide());

  cellSummary.addInfoButtonOnClick();
  
  $('.bigtable').hide();
</script>

<script>
  $ (document).ready(function() {
    // $('#slide_info_'+id_type+'_'+id_val).trigger( "click" );
    // console.log('#slide_info'+id_type+'_'+id_val);
    // console.log($('#slide_info'+id_type+'_'+id_val))

  });
</script>

labeller/templates/labeller/partials/export_project_data.html
<button class='export_button' id='{{ project.id }}'>Export project</button>


<script>

  $('.export_button').click(function(){
      console.log($(this).attr('id'));
      var project_id = $(this).attr('id');
      $.get("/export_project_data/", {'project_id':project_id}, function(json){

        console.log('button_export_handler callback');

        console.log(json['filename']);

        window.location.href = json['filename']

      });

  });
  

</script>

labeller/templates/labeller/partials/help_display.html
{% load static %}
<img id="helpscreen" style="display:none;" src="{% static 'labeller/images/Reference_maturation.png' %}" />

<script>

class HelpDisplay {
	static toggle () {
		console.log("help display", $("#helpscreen"), $("#helpscreen").is(":visible"))
		if ($("#helpscreen").is(":visible")){
			$("#helpscreen").fadeOut(500);
		}
		else{
			$("#helpscreen").fadeIn(500);
		}
	}
}

$('#helpscreen').click(function() { 
    $(this).fadeOut(500);
});

window.addEventListener('keyup', (e) => {
		if (e.code == "KeyH") {
			HelpDisplay.toggle();
		} 
});

</script>

labeller/templates/labeller/partials/main_lineages_horizontal.html
<!-- <p id="additional_instructions">Press left and right arrows to change cell</p>
<p id="additional_instructions">Click on cell to select it, or to create a new cell</p>
 -->
<!-- <h2 class="horizontal_list_category">Hematopoietic Lineage Lists</h2> -->

<h2 id="h2_unlabelled">Unlabelled</h2>
<div id="unlabelled_cells_inline" class="inline_cells"></div>

<h2 id="h2_myeloid">Myeloid</h2>
<div id="myeloid_cells_inline" class="inline_cells"></div>

<h2 id="h2_lymphoid">Lymphoid</h2>
<div id="lymphoid_cells_inline" class="inline_cells"></div>

<h2 id="h2_erythroid">Erythroid</h2>
<div id="erythroid_cells_inline" class="inline_cells"></div>

<h2 id="h2_megakaryocytic">Megakaryocytic</h2>
<div id="megakaryocytic_cells_inline" class="inline_cells"></div>

<h2 id="h2_misc">Miscelaneous</h2>
<div id="misc_cells_inline" class="inline_cells"></div>

<!-- <h2 class="horizontal_list_category">Specific Cell Type Lists</h2> -->
<div id="celltype_inline_container"></div>


{% load static %}
<!-- <script src="{% static 'labeller/Cell.js' %}"></script>
 -->
<script>
console.log('entering horizontal_cells.html javascript');

class HorizontalCellList {

	
	static nextCell(offset) {
    console.log('entering next cell');

		if (offset !=1 && offset != -1){
			console.log("Error in HorizontalCellList:nextCell - wrong offset", offset);
			return false;
		}

    if ($('.clicked_cell').length==0) {
        console.log('No clicked_cell in HorizontalCellList.nextCell')
        return;
      }
    if ($('.clicked_cell').length>1){
        console.log('Too many clicked_cell objects in HorizontalCellList.nextCell', $('.clicked_cell'))
        return;
    }

    var cell = $('.clicked_cell')

		{% comment %} if (cell.siblings.length == 0) {
			console.log("cell has no siblings")
			return false;
		
		} {% endcomment %}

		if (offset == 1 && cell.next().length ==1) {
//				var current_cell = cell.next();
				var cid = Cell.getCIDfromDivID(cell.next()[0]);
				Cell.selectCellByCID(cid);
        cell.removeClass('clicked_cell');
        cell.next().addClass('clicked_cell');
				return;
			}

			else if (offset == -1 && cell.prev().length ==1) {
				var cid = Cell.getCIDfromDivID(cell.prev()[0]);
				Cell.selectCellByCID(cid);
        cell.removeClass('clicked_cell');
        cell.prev().addClass('clicked_cell');
				return;
		}

		return;
	}

	static addKeyboardEventListeners(){
    {% comment %} window.addEventListener('keydown', function(e) {
      if(e.key === 'r' && e.ctrlKey) {
        e.preventDefault();
    }
    }); 
	{% endcomment %}
    window.addEventListener('keydown', function(e) {
      if(e.keyCode == 32 && e.target == document.body) {
        e.preventDefault();
      }
    });

			window.addEventListener('keyup', (e) => {
        console.log('horizontal key pressed event in main_lineages_horizontal');
       

				var code = e.code;
        
				switch(code) {
					
					case "ArrowLeft": HorizontalCellList.nextCell(-1);  break;
					case "ArrowRight": HorizontalCellList.nextCell(1); break;
					//case "Enter": nextRegion(); break;
          case "Space": HorizontalCellList.selectFirstUnlabelledCell(); break;
          case "Backslash": Cell.deleteCellByCID(Cell.currentCellCID()); break;
				}
			});
	}

	static cellListItemClickHandler(jq_obj){
		console.log("this item was clicked on", jq_obj);
		var cid = Cell.extractCIDFromJQueryObjectID(jq_obj);
    console.log($('.clicked_cell'))
 		Cell.selectCellByCID(cid);
    $('.clicked_cell').removeClass('clicked_cell');
    jq_obj.addClass('clicked_cell');
	}


	static selectFirstUnlabelledCell(){
		if ($(".cell_list_item.unlabelled").first().length>0){
			var cid = Cell.extractCIDFromJQueryObjectID($(".cell_list_item.unlabelled").first());
			Cell.selectCellByCID(cid);
      $('.clicked_cell').removeClass('clicked_cell');
      $(".cell_list_item.unlabelled").first().addClass('clicked_cell');
		}
	}

	static populateCellLists (cells_json, cell_types_json){
		//console.log('entering populatCellList', cells_json, cell_types_json);
		// console.log('entering populatCellList');
		var cells = Cell.LoadCellsFromJson(cells_json, cell_types_json);
		
    console.log('cells', cells)
		var counter = 1;
		for (var key in cells) {
			var cell = cells[key];
			console.log(cell)
			var cid = cell.getCID();
			var cell_div = cell.getDivForCellList();
			var jq_obj = $("#"+cell.getLineage()+"_cells_inline").append(cell_div);

			var jq_obj_celltype = $("#"+cell.cell_type+"_cells_inline").append(cell_div);
      //console.log(jq_obj, jq_obj_celltype)
		}

		$('.cell_list_item').on('click', function (){
			HorizontalCellList.cellListItemClickHandler($(this))
		});
    Cell.UpdateHorizontalCellCounts();
	}

	static addCellClassHorizontalRows() {
		for (var key in Cell.classLabelDict) {
			//console.log('meow', key, Cell.classLabelDict[key])
			var temp_div = '<h2 id="h2_'+key+'">'+Cell.classLabelDict[key]+'</h2><div id="'+key+'_cells_inline" class="inline_cells"></div>'
			$("#celltype_inline_container").append(temp_div);
		}
	}


}

$ (document).ready(function() {
	HorizontalCellList.addCellClassHorizontalRows();
	if ('{{cells_json}}'!='none') {		
	 	var cells_json = '{{cells_json}}';	 
	 	var celltypes_json = '{{celltypes_json}}';	
	 	// console.log('main_lineages_horizontal ready cells_json', cells_json)
		// console.log('main_lineages_horizontal ready celltypes_json', celltypes_json)
	 	// console.log(celltypes_json)
 		// HorizontalCellList.addCellClassHorizontalRows();
 		HorizontalCellList.populateCellLists(cells_json, celltypes_json);
 		//Cell.UpdateHorizontalCellCounts();
 		HorizontalCellList.addKeyboardEventListeners();
 		HorizontalCellList.selectFirstUnlabelledCell();
	}
});
</script>

labeller/templates/labeller/partials/mini_counter.html
<div id="mini_counter" class="purple_box">
	<h2>Cell Counter</h2>
	<div id='counter'></div>
	<div id='ME_ratio'></div>
</div>	

<script>

$ (document).ready(function() {
	console.log('entering minicounter scripts');
	CellCounter.buildpageCounter();
});

</script>

labeller/templates/labeller/partials/region_counter.html
{% load static %}
<script>
	var regions_json = '{{regions_json}}';
	console.log(regions_json);
</script>

<script src="{% static 'labeller/Region.js' %}"></script>
<script src="{% static 'labeller/partials/region_counter.js' %}"></script>

<div id="region_counter" class="purple_box">
	<h2>Region Counter</h2>
	<h3 id="Complete_Regions_Segmentation" class="counter"></h3>
	<h3 id="Incomplete_Regions_Segmentation" class="counter"></h3>
	<h3 id="Complete_Regions_Classification" class="counter"></h3>
	<h3 id="Incomplete_Regions_Classification" class="counter"></h3>
</div>	

labeller/templates/labeller/partials/region_list.html
<h2>Regions {{ user.username }} | {{ regions|length }}</h2>

<div id="regions" class="container-fluid">



      {% for region in regions %}

        {% if user.is_authenticated %}
        {% if user.id == region.created_by.id %} 

          <script>
            region = new Region("{{region.rid}}", "{{region.image.url}}");
            region.prependRegionDivToJQuerySelector("#regions");
          </script>

        {% endif %}
        {% endif %}

      {% empty %}
        <li id="no_regions_added_li">No regions have been added yet</li>
      {% endfor %}




</div>